version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/TodoAPI/TodoAPI.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./src/TodoAPI/TodoAPI.csproj
artifacts:
- path: src\TodoAPI\bin\Debug\netcoreapp2.1\publish
  name: Robrownn-TodoAPI

clone_depth: 1
deploy:
- provider: AzureAppServiceZipDeploy
  appservice_environment: false
  website: robrownntodoapi
  username: RobrownnTodoAPI\robrownn
  password:
    secure: oOYhtmDObxBmcDxmZZ2yig==
  artifact: Robrownn-TodoAPI